---
url: https://jekyll.template
name: Jekyll Template
permalink: pretty
relative_permalinks: false
timezone: Etc/UTC

safe: true
lsi: false
markdown: kramdown

sass:
  style: compressed

kramdown:
  input: GFM

collections:
  pages:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      seo:
        description: "Yay! You're on Jekyll!"
        image: "/public/images/social/og-icon.jpg"

includes:
  - assets

exclude:
  - .github/
  - .idea/
  - _js/
  - bin/
  - config/
  - lib/
  - node_modules/
  - resources/
  - vendor/
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - package-lock.json
  - Procfile.dev
  - README.md
  - Rakefile
