---
url: https://nimblehq.co
name: Jekyll Template
permalink: pretty
relative_permalinks: false
timezone: Etc/UTC

# Required to use local plugins
safe: false

lsi: false
markdown: kramdown

sass:
  style: compressed

kramdown:
  # All config options: https://jekyllrb.com/docs/configuration/markdown/
  input: GFM
  parse_block_html: true
  auto_ids: false

collections:
  pages:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      seo:
        description: "Yay! You're on Jekyll!"
        image: "/public/images/social/og-icon.jpg"

includes:
  - assets

exclude:
  - .github/
  - .idea/
  - _js/
  - bin/
  - config/
  - lib/
  - node_modules/
  - resources/
  - vendor/
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - package-lock.json
  - postcss.config.js
  - Procfile.dev
  - README.md
  - Rakefile
  - tailwind.config.js
